global_defs {
    enable_script_security
    max_auto_priority 99
    router_id blinky
    script_user root
}

vrrp_script AdGuardHome {
    script "/usr/local/bin/keepalived/throwawaydeadd AdGuardHome check"
    interval 5
    weight -10
    timeout 4
    rise 12
    fall 2
}

vrrp_script pihole-FTL {
    script "/usr/local/bin/keepalived/throwawaydeadd pihole-FTL check"
    interval 5
    weight -10
    timeout 4
    rise 12
    fall 2
}

vrrp_script unbound {
    script "/usr/local/bin/keepalived/throwawaydeadd unbound check"
    interval 5
    weight -10
    timeout 4
    rise 12
    fall 2
}

vrrp_instance VIP11 {
    state MASTER
    interface eth0
    virtual_router_id 11
    priority 150
    advert_int 2
    unicast_src_ip 192.168.1.10
    unicast_peer {
        192.168.1.20
        192.168.1.30
        192.168.1.40
    }
    authentication {
        auth_type PASS
        auth_pass N9d8Byfb
    }
    virtual_ipaddress {
        192.168.1.11/24
    }
    track_script {
        pihole-FTL
    }
    #notify "/usr/local/bin/keepalived/throwawaydeadd pihole-FTL notify"
}

vrrp_instance VIP22 {
    state BACKUP
    interface eth0
    virtual_router_id 22
    priority 135
    advert_int 2
    unicast_src_ip 192.168.1.10
    unicast_peer {
        192.168.1.20
        192.168.1.30
        192.168.1.40
    }
    authentication {
        auth_type PASS
        auth_pass jB5rg8A3
    }
    virtual_ipaddress {
        192.168.1.22/24
    }
    track_script {
        pihole-FTL
    }
    #notify "/usr/local/bin/keepalived/throwawaydeadd pihole-FTL notify"
}

vrrp_instance VIP33 {
    state BACKUP
    interface eth0
    virtual_router_id 33
    priority 140
    advert_int 2
    unicast_src_ip 192.168.1.10
    unicast_peer {
        192.168.1.20
        192.168.1.30
        192.168.1.40
    }
    authentication {
        auth_type PASS
        auth_pass ZsG94ty3
    }
    virtual_ipaddress {
        192.168.1.33/24
    }
    track_script {
        unbound
    }
    #notify "/usr/local/bin/keepalived/throwawaydeadd unbound notify"
}

vrrp_instance VIP44 {
    state BACKUP
    interface eth0
    virtual_router_id 44
    priority 145
    advert_int 2
    unicast_src_ip 192.168.1.10
    unicast_peer {
        192.168.1.20
        192.168.1.30
        192.168.1.40
    }
    authentication {
        auth_type PASS
        auth_pass 598whthY
    }
    virtual_ipaddress {
        192.168.1.44/24
    }
    track_script {
        unbound
    }
    #notify "/usr/local/bin/keepalived/throwawaydeadd unbound notify"
}

vrrp_instance VIP100 {
    state BACKUP
    interface eth0
    virtual_router_id 100
    priority 135
    advert_int 2
    unicast_src_ip 192.168.1.10
    unicast_peer {
        192.168.1.20
        192.168.1.30
        192.168.1.40
    }
    authentication {
        auth_type PASS
        auth_pass YEP54ZDq
    }
    virtual_ipaddress {
        192.168.1.100/24
    }
    track_script {
        AdGuardHome
    }
    #notify "/usr/local/bin/keepalived/throwawaydeadd AdGuardHome notify"
}